default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minesweeper_development
  host: localhost
  username: <%= ENV['USER'] %>  # This will use your system username
  password:  # Leave blank if no password set

test:
  <<: *default
  database: minesweeper_test

production:
  <<: *default
  database: minesweeper_production
  username: minesweeper
  password: <%= ENV["MINESWEEPER_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
